INSERT INTO "CourseTag" (id, name) VALUES
    (gen_random_uuid(), 'Programming'),
    (gen_random_uuid(), 'UI'),
    (gen_random_uuid(), 'UX'),
    (gen_random_uuid(), 'Web Design'),
    (gen_random_uuid(), 'Web Development'),
    (gen_random_uuid(), 'Markup'),
    (gen_random_uuid(), 'HTML'),
    (gen_random_uuid(), 'Architecture'),
    (gen_random_uuid(), 'DevOps'),
    (gen_random_uuid(), 'Algo'),
    (gen_random_uuid(), 'DSA'),
    (gen_random_uuid(), 'Beginner-friendly'),
    (gen_random_uuid(), 'Advanced'),
    (gen_random_uuid(), 'Web accessibility'),
    (gen_random_uuid(), 'Software Development'),
    (gen_random_uuid(), 'Cloud computing'),
    (gen_random_uuid(), 'Machine Learning'),
    (gen_random_uuid(), 'AI');